/**
 * Mock Data for Table Management
 * Used for UI development without backend
 */

import {
  Table,
  Area,
  Reservation,
  TableStatus,
  TableShape,
  TableSize,
  ReservationStatus,
} from '@/types/settings/table-management.types';

export const MOCK_AREAS: Area[] = [
  {
    id: 'area_main',
    restaurant_id: 'rest_001',
    name: 'Main Dining',
    description: 'Primary dining area',
    color: '#4CAF50',
    display_order: 1,
    is_active: true,
    allow_reservations: true,
    table_count: 15,
    total_capacity: 60,
    available_tables: 9,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 'area_vip',
    restaurant_id: 'rest_001',
    name: 'VIP Section',
    description: 'Exclusive VIP dining area',
    color: '#9C27B0',
    display_order: 2,
    is_active: true,
    allow_reservations: true,
    table_count: 3,
    total_capacity: 18,
    available_tables: 1,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 'area_patio',
    restaurant_id: 'rest_001',
    name: 'Outdoor Patio',
    description: 'Outdoor dining area',
    color: '#FF9800',
    display_order: 3,
    is_active: true,
    allow_reservations: true,
    table_count: 7,
    total_capacity: 28,
    available_tables: 5,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 'area_bar',
    restaurant_id: 'rest_001',
    name: 'Bar Area',
    description: 'Bar seating area',
    color: '#607D8B',
    display_order: 4,
    is_active: true,
    allow_reservations: false,
    table_count: 0,
    total_capacity: 6,
    available_tables: 0,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
];

export const MOCK_TABLES: Table[] = [
  // Main Dining - Row 1
  {
    id: 'table_001',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '1',
    capacity: 4,
    status: TableStatus.AVAILABLE,
    shape: TableShape.SQUARE,
    size: TableSize.MEDIUM,
    position: { x: 100, y: 240, gridX: 0, gridY: 0 },
    is_active: true,
    allow_online_booking: true,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_002',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '2',
    capacity: 2,
    status: TableStatus.OCCUPIED,
    shape: TableShape.SQUARE,
    size: TableSize.SMALL,
    position: { x: 280, y: 240, gridX: 1, gridY: 0 },
    is_active: true,
    allow_online_booking: true,
    current_order_id: 'order_001',
    assigned_server_id: 'server_001',
    customer_name: 'John Smith',
    occupied_since: new Date(Date.now() - 45 * 60 * 1000),
    estimated_duration: 90,
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_003',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '3',
    capacity: 6,
    status: TableStatus.OCCUPIED,
    shape: TableShape.RECTANGLE,
    size: TableSize.LARGE,
    position: { x: 460, y: 240, gridX: 2, gridY: 0 },
    is_active: true,
    allow_online_booking: true,
    current_order_id: 'order_002',
    assigned_server_id: 'server_002',
    customer_name: 'Johnson Family',
    occupied_since: new Date(Date.now() - 80 * 60 * 1000),
    estimated_duration: 120,
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_004',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '4',
    capacity: 4,
    status: TableStatus.AVAILABLE,
    shape: TableShape.ROUND,
    size: TableSize.MEDIUM,
    position: { x: 640, y: 240, gridX: 3, gridY: 0 },
    is_active: true,
    allow_online_booking: true,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_005',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '5',
    capacity: 8,
    status: TableStatus.OCCUPIED,
    shape: TableShape.RECTANGLE,
    size: TableSize.LARGE,
    position: { x: 820, y: 240, gridX: 4, gridY: 0 },
    is_active: true,
    allow_online_booking: true,
    current_order_id: 'order_003',
    assigned_server_id: 'server_001',
    customer_name: 'Corporate Group',
    occupied_since: new Date(Date.now() - 125 * 60 * 1000),
    estimated_duration: 180,
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },

  // Main Dining - Row 2
  {
    id: 'table_006',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '6',
    capacity: 2,
    status: TableStatus.AVAILABLE,
    shape: TableShape.SQUARE,
    size: TableSize.SMALL,
    position: { x: 100, y: 380, gridX: 0, gridY: 1 },
    is_active: true,
    allow_online_booking: true,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_007',
    restaurant_id: 'rest_001',
    area_id: 'area_main',
    table_number: '7',
    capacity: 4,
    status: TableStatus.OCCUPIED,
    shape: TableShape.ROUND,
    size: TableSize.MEDIUM,
    position: { x: 280, y: 380, gridX: 1, gridY: 1 },
    is_active: true,
    allow_online_booking: true,
    current_order_id: 'order_004',
    assigned_server_id: 'server_003',
    customer_name: 'Mike Johnson',
    occupied_since: new Date(Date.now() - 30 * 60 * 1000),
    estimated_duration: 90,
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },

  // VIP Section
  {
    id: 'table_008',
    restaurant_id: 'rest_001',
    area_id: 'area_vip',
    table_number: '8',
    capacity: 6,
    status: TableStatus.RESERVED,
    shape: TableShape.OVAL,
    size: TableSize.LARGE,
    position: { x: 460, y: 400, gridX: 2, gridY: 1 },
    is_active: true,
    allow_online_booking: true,
    current_reservation_id: 'res_001',
    customer_name: 'VIP Guest',
    notes: 'VIP table - special attention required',
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_009',
    restaurant_id: 'rest_001',
    area_id: 'area_vip',
    table_number: '9',
    capacity: 8,
    status: TableStatus.AVAILABLE,
    shape: TableShape.RECTANGLE,
    size: TableSize.LARGE,
    position: { x: 620, y: 400, gridX: 3, gridY: 1 },
    is_active: true,
    allow_online_booking: true,
    notes: 'VIP table',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },

  // Patio Tables
  {
    id: 'table_010',
    restaurant_id: 'rest_001',
    area_id: 'area_patio',
    table_number: '10',
    capacity: 4,
    status: TableStatus.AVAILABLE,
    shape: TableShape.ROUND,
    size: TableSize.MEDIUM,
    position: { x: 120, y: 580, gridX: 0, gridY: 2 },
    is_active: true,
    allow_online_booking: true,
    notes: 'Outdoor seating',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
  {
    id: 'table_011',
    restaurant_id: 'rest_001',
    area_id: 'area_patio',
    table_number: '11',
    capacity: 4,
    status: TableStatus.OCCUPIED,
    shape: TableShape.SQUARE,
    size: TableSize.MEDIUM,
    position: { x: 260, y: 580, gridX: 1, gridY: 2 },
    is_active: true,
    allow_online_booking: true,
    current_order_id: 'order_005',
    assigned_server_id: 'server_002',
    customer_name: 'Sarah Williams',
    occupied_since: new Date(Date.now() - 20 * 60 * 1000),
    notes: 'Outdoor seating',
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
    created_by: 'admin_001',
    updated_by: 'admin_001',
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res_001',
    restaurant_id: 'rest_001',
    table_id: 'table_008',
    customer_name: 'VIP Guest',
    customer_phone: '+1-555-0001',
    customer_email: 'vip@example.com',
    party_size: 6,
    reservation_date: new Date(),
    reservation_time: '19:00',
    duration: 120,
    status: ReservationStatus.CONFIRMED,
    occasion: 'Anniversary',
    special_requests: 'Window seating, champagne on arrival',
    dietary_restrictions: ['Vegetarian'],
    send_confirmation: true,
    reminder_time: 2,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    created_by: 'staff_001',
  },
];
